In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('fraud_data.csv', sep=';')
df

,merchan_id,avg_amount_days,transaction_amount,is_declined,number_declines_days,foreign_transaction,high_risk_countries,daily_chbk_avg_amt,6m_avg_chbk_amt,6m_chbk_freq,is_fradulent
0,3160040998,100.0,3000.0,no,5,yes,yes,0,0.0,0,fraudulent
1,3160040998,100.0,4300.0,no,5,yes,yes,0,0.0,0,fraudulent
2,3160041896,185.5,4823.0,yes,5,no,no,0,0.0,0,fraudulent
3,3160141996,185.5,5008.5,yes,8,no,no,0,0.0,0,fraudulent
4,3160241992,500.0,26000.0,no,0,yes,yes,800,677.2,6,fraudulent
...,...,...,...,...,...,...,...,...,...,...,...
3070,6661273532,500.0,11000.0,yes,0,no,no,754,585.0,7,non-fraudulent
3071,6661273532,800.0,0.0,yes,0,no,no,754,585.0,7,non-fraudulent
3072,6661273533,800.0,20800.0,yes,0,no,no,754,585.0,7,non-fraudulent
3073,6661273532,1500.0,12000.0,yes,0,yes,yes,754,585.0,7,non-fraudulent
3074,6661273533,1500.0,36000.0,yes,0,yes,yes,754,585.0,7,non-fraudulent

In [13]:
df.drop(columns=['merchan_id'],inplace=True)

In [14]:
df.shape

(3075, 10)

In [15]:
df.size

30750

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3075 entries, 0 to 3074
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avg_amount_days       3075 non-null   float64
 1   transaction_amount    3075 non-null   float64
 2   is_declined           3075 non-null   str
 3   number_declines_days  3075 non-null   int64
 4   foreign_transaction   3075 non-null   str
 5   high_risk_countries   3075 non-null   str
 6   daily_chbk_avg_amt    3075 non-null   int64
 7   6m_avg_chbk_amt       3075 non-null   float64
 8   6m_chbk_freq          3075 non-null   int64
 9   is_fradulent          3075 non-null   str
dtypes: float64(3), int64(3), str(4)
memory usage: 299.6 KB

In [17]:
df.columns

Index(['avg_amount_days', 'transaction_amount', 'is_declined',
       'number_declines_days', 'foreign_transaction', 'high_risk_countries',
       'daily_chbk_avg_amt', '6m_avg_chbk_amt', '6m_chbk_freq',
       'is_fradulent'],
      dtype='str')

In [18]:
df.isnull().sum()

avg_amount_days         0
transaction_amount      0
is_declined             0
number_declines_days    0
foreign_transaction     0
high_risk_countries     0
daily_chbk_avg_amt      0
6m_avg_chbk_amt         0
6m_chbk_freq            0
is_fradulent            0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(1)

In [20]:
df.boxplot()

In [21]:
df.is_fradulent.value_counts()

is_fradulent
non-fraudulent    2627
fraudulent         448
Name: count, dtype: int64

In [22]:
df.high_risk_countries.value_counts()

high_risk_countries
no     2870
yes     205
Name: count, dtype: int64

In [23]:
df.foreign_transaction.value_counts()

foreign_transaction
no     2369
yes     706
Name: count, dtype: int64

In [24]:
df.is_declined.value_counts()

is_declined
no     3018
yes      57
Name: count, dtype: int64

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['is_fradulent']=le.fit_transform(df['is_fradulent'])
df['high_risk_countries']=le.fit_transform(df['high_risk_countries'])
df['foreign_transaction']=le.fit_transform(df['foreign_transaction'])
df['is_declined']=le.fit_transform(df['is_declined'])
df

,avg_amount_days,transaction_amount,is_declined,number_declines_days,foreign_transaction,high_risk_countries,daily_chbk_avg_amt,6m_avg_chbk_amt,6m_chbk_freq,is_fradulent
0,100.0,3000.0,0,5,1,1,0,0.0,0,0
1,100.0,4300.0,0,5,1,1,0,0.0,0,0
2,185.5,4823.0,1,5,0,0,0,0.0,0,0
3,185.5,5008.5,1,8,0,0,0,0.0,0,0
4,500.0,26000.0,0,0,1,1,800,677.2,6,0
...,...,...,...,...,...,...,...,...,...,...
3070,500.0,11000.0,1,0,0,0,754,585.0,7,1
3071,800.0,0.0,1,0,0,0,754,585.0,7,1
3072,800.0,20800.0,1,0,0,0,754,585.0,7,1
3073,1500.0,12000.0,1,0,1,1,754,585.0,7,1
3074,1500.0,36000.0,1,0,1,1,754,585.0,7,1

In [26]:
x=df.drop(columns='is_fradulent')
y=df['is_fradulent']

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=50)

In [28]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
pred_train=lr.predict(x_train)
pred_test=lr.predict(x_test)
from sklearn.metrics import *
print("Train Acc is ",accuracy_score(y_train,pred_train))
print(classification_report(y_train,pred_train))
print("Test Acc is ",accuracy_score(y_test,pred_test))
print(classification_report(y_test,pred_test))

Train Acc is  0.9857723577235772
              precision    recall  f1-score   support

           0       0.97      0.93      0.95       356
           1       0.99      0.99      0.99      2104

    accuracy                           0.99      2460
   macro avg       0.98      0.96      0.97      2460
weighted avg       0.99      0.99      0.99      2460

Test Acc is  0.9788617886178862
              precision    recall  f1-score   support

           0       0.95      0.90      0.93        92
           1       0.98      0.99      0.99       523

    accuracy                           0.98       615
   macro avg       0.97      0.95      0.96       615
weighted avg       0.98      0.98      0.98       615

In [29]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
pred=dt.predict(x_train)
pred
from sklearn.metrics import *
print("Train Acc is ",accuracy_score(y_train,pred_train))
print(classification_report(y_train,pred_train))
print("Test Acc is ",accuracy_score(y_test,pred_test))
print(classification_report(y_test,pred_test))

Train Acc is  0.9857723577235772
              precision    recall  f1-score   support

           0       0.97      0.93      0.95       356
           1       0.99      0.99      0.99      2104

    accuracy                           0.99      2460
   macro avg       0.98      0.96      0.97      2460
weighted avg       0.99      0.99      0.99      2460

Test Acc is  0.9788617886178862
              precision    recall  f1-score   support

           0       0.95      0.90      0.93        92
           1       0.98      0.99      0.99       523

    accuracy                           0.98       615
   macro avg       0.97      0.95      0.96       615
weighted avg       0.98      0.98      0.98       615

In [30]:
#Applying Scaler & Training Model
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

sc = StandardScaler()

# Fit scaler only on training data, then transform
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

lr1 = LogisticRegression()
lr1.fit(x_train_scaled, y_train)
pred_train = lr1.predict(x_train_scaled)
pred_test = lr1.predict(x_test_scaled)

print("Train Acc is ",accuracy_score(y_train,pred_train))
print(classification_report(y_train,pred_train))
print("Test Acc is ",accuracy_score(y_test,pred_test))
print(classification_report(y_test,pred_test))

Train Acc is  0.9878048780487805
              precision    recall  f1-score   support

           0       0.97      0.94      0.96       356
           1       0.99      1.00      0.99      2104

    accuracy                           0.99      2460
   macro avg       0.98      0.97      0.98      2460
weighted avg       0.99      0.99      0.99      2460

Test Acc is  0.9902439024390244
              precision    recall  f1-score   support

           0       0.98      0.96      0.97        92
           1       0.99      1.00      0.99       523

    accuracy                           0.99       615
   macro avg       0.99      0.98      0.98       615
weighted avg       0.99      0.99      0.99       615

In [31]:
import joblib
joblib.dump(lr1, "model.pkl")

['model.pkl']

In [32]:
# Save scaler
joblib.dump(sc, "scaler.pkl")

['scaler.pkl']

In [33]:
df.columns

Index(['avg_amount_days', 'transaction_amount', 'is_declined',
       'number_declines_days', 'foreign_transaction', 'high_risk_countries',
       'daily_chbk_avg_amt', '6m_avg_chbk_amt', '6m_chbk_freq',
       'is_fradulent'],
      dtype='str')

In [36]:
#!/usr/bin/env python
# coding: utf-8
# In[ ]:
import streamlit as st
import joblib
import numpy as np
# Load model and scaler
model = joblib.load("model.pkl")
scaler = joblib.load("scaler.pkl")

st.set_page_config(page_title="Fraud Data Prediction", page_icon="")

st.title("Fraud Data Prediction")

st.write("Enter the feature values below to predict the data.")

# User Inputs
avg_amount_days = st.number_input("avg_amount_days", min_value=0.0, format="%.4f")
transaction_amount = st.number_input("transaction_amount", min_value=0.0, format="%.4f")
is_declined = st.number_input("is_declined", min_value=0.0, format="%.4f")
number_declines_days = st.number_input("number_declines_days", min_value=0.0, format="%.4f")
foreign_transaction = st.number_input("foreign_transaction", min_value=0.0, format="%.4f")
high_risk_countries = st.number_input("high_risk_countries", min_value=0.0, format="%.4f")
daily_chbk_avg_amt = st.number_input("daily_chbk_avg_amt", min_value=0.0, format="%.4f")
Sm_avg_chbk_amt = st.number_input("6m_avg_chbk_amt", min_value=0.0, format="%.4f")
Sm_chbk_freq = st.number_input("6m_chbk_freq", min_value=0.0, format="%.4f")

if st.button("Predict Diagnosis"):

    input_data = np.array([[
        avg_amount_days,
        transaction_amount,
        is_declined,
        number_declines_days,
        foreign_transaction,
        high_risk_countries,
        daily_chbk_avg_amt,
        Sm_avg_chbk_amt,
        Sm_chbk_freq,
    ]])

    # Scale the input
    input_scaled = scaler.transform(input_data)

    # Predict
    prediction = model.predict(input_scaled)

    # Display Result
    if prediction[0] == "M" or prediction[0] == 1:
        st.error("🔴 fradulent: Yes, fradulent")
    else:
        st.success("🟢 fradulent: It is Safe")

2026-10-01 16:55:22.306 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:22.308 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.686
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Dell\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-10-01 16:55:23.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.704 Session state does not function when running a script without `streamlit run`
2026-10-01 16:55:23.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.711 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.712 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.715 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.717 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.730 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.734 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.744 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.749 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.749 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.750 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.751 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.754 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.755 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.756 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.759 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.761 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.766 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.774 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-10-01 16:55:23.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.